### ISSUE TITLE
Creatin mini ImageNet_LT

### ISSUE THREAD

**Issue by Angelina1996** [rahulvigneswaran/TailCalibX#10]
Hi Rahul,
Just wondering if you could help with the following error in creating a mini imageNet_LT dataset. I am using imageNet2012 which has 2 directories,
![imageNet](https://user-images.githubusercontent.com/66866219/203230847-2fbf245b-a447-469d-a87e-16291e363909.JPG)
 train and val.
ImageNet Directory pic is also provided below the error message.
Error 
(base) [Angelina@rob-gpu Notebooks]$ python create_mini_ImageNet_LT.py
Traceback (most recent call last):
  File "create_mini_ImageNet_LT.py", line 69, in <module>
    train_x, test_x, train_y, test_y = train_test_split(final_1, labels_1, train_size=train_split_ratio, test_size=test_split_ratio, stratify=labels_1)
  File "/home/Angelina/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2130, in train_test_split
    n_train, n_test = _validate_shuffle_split(n_samples, test_size, train_size,
  File "/home/Angelina/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 1810, in _validate_shuffle_split
    raise **ValueError( ValueError: With n_samples=0, test_size=0.19999999999999996 and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.**

**Comment by Angelina1996** [comment]
Hi just wondering if anyone has created the mini imagenet_Lt dataset?

**Comment by Angelina1996** [comment]
Hi Rahul,
Could you please guide the contents of the following directory:
root = "/home/rahul_intern/Imagenet/mini_imagenet"   # Should point to the dir in which your ImagNet is.
What are the directories or files in mini_imagenet folder.
